### ISSUE TITLE
Different frame 

### ISSUE THREAD

**Issue by Silence667** [thomsmits/lavaframe#1]
Hello I have a 30x40cm Ribba Frame from Ikea and a diffusorplate for it. What I need to change in the Programmcode that I could use my Frame? 
Thanks for you help.

**Comment by Springwald** [comment]
Hello, 

The size of the frame rather determines how you choose the distances and the diffusion material.

For the software only the number of LEDs should be relevant:
If you use a different number, you would have to enter that in the code as well.

Best regards
Daniel

**Comment by Silence667** [comment]
Thank you! 
Now I have change LF_COLS and LF_ROWS to my framesize and load the Files into my Arduino IDE to transfer the files on my NodeMCU. Now i have some Error at verifying. 
Some Errors:

C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\lavaframe.ino:18:10: fatal error: FastLED.h: No such file or directory
   18 | #include <FastLED.h>
      |          ^~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: FastLED.h: No such file or directory

_________________________________________________________________

In file included from C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\lavaframe.ino:21:
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.h:45:5: error: 'CRGB' does not name a type
   45 |     CRGB leds[NUM_LEDS];
      |     ^~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino: In member function 'void Frame::push_to_strip()':
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:33:13: error: 'leds' was not declared in this scope
   33 |             leds[_tgt(x, y)] = CRGB(p->r, p->g, p->b);
      |             ^~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:33:32: error: 'CRGB' was not declared in this scope
   33 |             leds[_tgt(x, y)] = CRGB(p->r, p->g, p->b);
      |                                ^~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:36:5: error: 'FastLED' was not declared in this scope
   36 |     FastLED.show();
      |     ^~~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino: In member function 'void Frame::setup()':
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:47:5: error: 'FastLED' was not declared in this scope
   47 |     FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
      |     ^~~~~~~
In file included from C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\lavaframe.ino:20:
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\hardware.h:21:25: error: 'WS2811' was not declared in this scope
   21 | #define LED_TYPE        WS2811
      |                         ^~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:47:21: note: in expansion of macro 'LED_TYPE'
   47 |     FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
      |                     ^~~~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\hardware.h:22:25: error: 'GRB' was not declared in this scope
   22 | #define COLOR_ORDER     GRB
      |                         ^~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:47:39: note: in expansion of macro 'COLOR_ORDER'
   47 |     FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
      |                                       ^~~~~~~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:47:52: error: 'leds' was not declared in this scope
   47 |     FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
      |                                                    ^~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:47:82: error: 'TypicalLEDStrip' was not declared in this scope
   47 |     FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
      |                                                                                  ^~~~~~~~~~~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:49:27: error: 'INPUT_PULLDOWN' was not declared in this scope; did you mean 'INPUT_PULLDOWN_16'?
   49 |     pinMode(BUTTON_1_PIN, INPUT_PULLDOWN);
      |                           ^~~~~~~~~~~~~~
      |                           INPUT_PULLDOWN_16
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino: In member function 'void Frame::loop()':
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:104:5: error: 'EVERY_N_MILLISECONDS' was not declared in this scope
  104 |     EVERY_N_MILLISECONDS( 500 ) { adjust_global_brightness(); }
      |     ^~~~~~~~~~~~~~~~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino: In member function 'void Frame::adjust_global_brightness()':
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:196:5: error: 'FastLED' was not declared in this scope
  196 |     FastLED.setBrightness(actual_Brightness);   // set master brightness control
      |     ^~~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino: In member function 'void Frame::testEEProm()':
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:230:20: error: could not convert 'EEPROM.EEPROMClass::begin(512)' from 'void' to 'bool'
  230 |   if (!EEPROM.begin(512))
      |        ~~~~~~~~~~~~^~~~~
      |                    |
      |                    void
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:230:20: error: in argument to unary !

exit status 1

Compilation error: 'CRGB' does not name a type

_______________________________________________

Please could you help me to get the Program running on my NodeMCU and the Lavaframe? 

Thanks for your help

**Comment by Springwald** [comment]
Hello,

this is not a problem specific to LavaFrame - you simply don't seem to have the FastLED library installed.

Best regards
Daniel

**Comment by Silence667** [comment]
Thanks for your help and after installing the fastled library the error is gone. Sorry, now i have a new Error :-( (I am a noob but i will learn) .
The Error:
___________________________________________________________________________________
In file included from c:\Users\SL\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\lavaframe.ino:18:
c:\Users\SL\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino: In member function 'void Frame::setup()':
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:49:27: error: 'INPUT_PULLDOWN' was not declared in this scope; did you mean 'INPUT_PULLDOWN_16'?
   49 |     pinMode(BUTTON_1_PIN, INPUT_PULLDOWN);
      |                           ^~~~~~~~~~~~~~
      |                           INPUT_PULLDOWN_16
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino: In member function 'void Frame::testEEProm()':
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:230:20: error: could not convert 'EEPROM.EEPROMClass::begin(512)' from 'void' to 'bool'
  230 |   if (!EEPROM.begin(512))
      |        ~~~~~~~~~~~~^~~~~
      |                    |
      |                    void
C:\Users\SL\Downloads\lavaframe-master\src\lavaframe\frame.ino:230:20: error: in argument to unary !

exit status 1

Compilation error: 'INPUT_PULLDOWN' was not declared in this scope; did you mean 'INPUT_PULLDOWN_16'?

_________________________________________________________________

Ich habe nochmal versucht, mich im Internet schlau zu machen, aber bin leider nicht wirklich auf Seiten gestoßen, die mir auch weitergeholfen haben. Liegt es vielleicht auch daran, dass ich einen NodeMCU verwende und keinen klassischen ESP32? 

Danke für Deine Hilfe.

**Comment by Silence667** [comment]
Habe ich die falsche Library installiert ?

**Comment by Silence667** [comment]
Benötige ich sonst noch grundlegende Bibliotheken, für das Projekt? Bisher konnte ich das vorherige Problem leider nicht lösen.

**Comment by thomsmits** [comment]
Die Architektur des NodeMCU ist anders als die des ESP32. So kann man beim NodeMCU nicht alle Pins auf Pulldown stellen, sondern nur Pin 16. Deswegen passen die im Programm benutzten `#define` nicht.

Ich würde einfach einen ESP32 nehmen, dann sollte alles klappen. Alternativ kann man die Software für den NodeMCU anpassen oder auch einen externen Pull-Down-Widerstand verwenden. Das liegt dann beim Anwender, nicht bei uns.

Ich sehe hier aber kein Issue in unserer Software, sondern in der verwendeten Plattform und schließe das Issue deswegen.

Schöne Grüße

  Thomas
